language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - osx
after_success:
  - yarn global add teraslice-cli
  - teraslice-cli assets build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
